// Generated by scripts/generate-mosaic-manifest.mjs. Do not edit manually.
export const MOSAIC_ASSETS = [
  {
    id: "mosaic-23dd3311-e2c5-4ba3-87bb-d056d3b75f32",
    name: "Mosaic 23DD3311",
    filename: "23DD3311-E2C5-4BA3-87BB-D056D3B75F32.PNG",
  },
  {
    id: "mosaic-3470ea07-2b30-4cce-89f7-664a6460c7df",
    name: "Mosaic 3470EA07",
    filename: "3470EA07-2B30-4CCE-89F7-664A6460C7DF.PNG",
  },
  {
    id: "mosaic-3a6ff20d-da5e-422e-9296-242af2e6c604",
    name: "Mosaic 3A6FF20D",
    filename: "3A6FF20D-DA5E-422E-9296-242AF2E6C604.PNG",
  },
  {
    id: "mosaic-5abdef81-b8c7-4387-af15-21882cc2401d",
    name: "Mosaic 5ABDEF81",
    filename: "5ABDEF81-B8C7-4387-AF15-21882CC2401D.PNG",
  },
  {
    id: "mosaic-8ed505ee-f994-46d5-8e0b-3cc8ec770a96",
    name: "Mosaic 8ED505EE",
    filename: "8ED505EE-F994-46D5-8E0B-3CC8EC770A96.PNG",
  },
  {
    id: "mosaic-8f6945d0-2e20-41d5-b499-b90527e428fe",
    name: "Mosaic 8F6945D0",
    filename: "8F6945D0-2E20-41D5-B499-B90527E428FE.PNG",
  },
  {
    id: "mosaic-c36940e8-5bf5-4568-abe7-5903ef3d5311",
    name: "Mosaic C36940E8",
    filename: "C36940E8-5BF5-4568-ABE7-5903EF3D5311.PNG",
  },
  {
    id: "mosaic-dc6e8362-3310-4453-a436-00d14a36ec66",
    name: "Mosaic DC6E8362",
    filename: "DC6E8362-3310-4453-A436-00D14A36EC66.PNG",
  },
  {
    id: "mosaic-dd99152f-96c9-46f5-b07b-ee7e4e076c04",
    name: "Mosaic DD99152F",
    filename: "DD99152F-96C9-46F5-B07B-EE7E4E076C04.PNG",
  },
] as const;
